version: "3.7"
services:
  # loki
  loki:
    container_name: engine_loki
    image: grafana/loki:3.2.1
    command:
      - -config.file=/mnt/config/loki-config.yaml
    ports:
      - 3100:3100
    volumes:
      - ./loki:/mnt/config
      - ./loki/data:/tmp/loki
  # prometheus
  prometheus:
    container_name: engine_prometheus
    image:  prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus/data