apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- deployment.yaml
- service.yaml
- service-monitor.yaml
