server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki地址:3100/loki/api/v1/push # 修改处

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          ai: mfu
          host_ip: 节点ip 地址 #修改处
          job: varlogs
          __path__: /var/log/run-2025*/files/output.log # 具体日志目录