version: "3.7"
services:
  # snmp-exporter
  snmp-exporter:
    container_name: snmp-exporter
    image: prom/snmp-exporter:latest
    restart: always
    ports:
      - 9116:9116
  # Collector
  otel-collector:
    container_name: otel-collector
    environment:
      GOMEMLIMIT: "24GiB" # 机器内存的80%
    image: otel/opentelemetry-collector-contrib:0.113.0
    restart: always
    depends_on:
      - snmp-exporter
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./gpu-server-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension