#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  labels:
#    app: nvidia-dcgm-exporter
#    release: prometheus-operator
#  name: nvidia-dcgm-exporter-label
#  namespace: gpu-operator
#spec:
#  endpoints:
#    - interval: 15s
#      path: /metrics
#      port: gpu-metrics
#      metricRelabelings:
#      - sourceLabels:
#        - __meta_kubernetes_pod_node_name
#        targetLabel: k8s-node-host
#  jobLabel: app
#  namespaceSelector:
#    matchNames:
#      - gpu-operator
#  selector:
#    matchLabels:
#      app: nvidia-dcgm-exporter